### ISSUE TITLE
Run local_map on ROS Hydro

### ISSUE THREAD

**Issue by Sadek92a** [lama-imr/lama_utilities#2]
Hi,
First off all, I want to thank you for your excellent package! It runs amazingly on ROS Indigo.

Next, I would like to run local_map on ROS Hydro so I copied the code on my workspace and run catkin_make. Unfortunately, it doesn't work.
Is that any way to run local_map on ROS Hydro ?

Thanks.

**Comment by galou** [comment]
Could you please provide more information about the issue?
Did you manage to compile the package?
Can you provide us with some log of the error?

**Comment by Sadek92a** [comment]
Finally I resolved the issue. You need to have map_ray_caster, lama_msgs and CGAL installed in order to run local_map. That's what I did and it works perfectly.
Thanks.

**Comment by imr-ctu** [comment]
`rosdep install` is your friend!
