### ISSUE TITLE
Building an Occupancy Grid using Hokuyo Laser Scanner

### ISSUE THREAD

**Issue by ktiwari9** [lama-imr/lama_utilities#4]
Hi there,
I am interested in a ROS Node that takes in the input from a Hokuyo Laser Scanner from RViZ/Gazebo and can visualize the Occupancy Grid in Rviz. I was looking through your packages and I was wondering if the local_map package can help me do this ?

Also, I am using ROS Hydro so is this project compatible with Hydro ?

**Comment by galou** [comment]
Hello,

yes, this is the aim of the `local_map` package.

The package wasn't tested with Hydro. Please report any problem so that we can maybe add the compatibility with Hydro. Thanks!
