### ISSUE TITLE
compiling local

### ISSUE THREAD

**Issue by kilmarnock** [lama-imr/lama_utilities#5]
Hi!
I tried to compile local_map via catkin_make. It complains about not finding lama_msgs. lama_msgs is referred in the CMakeLists:

```
find_package(catkin REQUIRED COMPONENTS
  lama_msgs
  nav_msgs
  roscpp
)
```

But the package is not provided. 

Edit:
It is in the repositories:
sudo apt-get install ros-indigo-lama-msgs

**Comment by Ocxs** [comment]
@kilmarnock Hi, I met the same error as you, could you tell me how solve it? Thanks in adavance.
